name: Build Alien Shooter Port

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write
  actions: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-22.04-arm

    steps:
    - uses: actions/checkout@v4

    - name: Build in Dev Container
      uses: devcontainers/ci@v0.3
      with:
        imageName: ghcr.io/${{ github.repository }}/devcontainer
        cacheFrom: ghcr.io/${{ github.repository }}/devcontainer
        push: always
        configFile: .devcontainer/devcontainer.json
        runCmd: |
          cmake .
          make -j$(nproc)

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: alienport-binary
        path: alienport
