name: Build Alien Shooter Port

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04-arm

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake pkg-config libsdl2-dev libgles2-mesa-dev libegl1-mesa-dev zlib1g-dev

    - name: Build
      run: |
        cmake .
        make -j$(nproc)

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: alienport-binary
        path: |
          alienport
          libpthread_preload.so
